/**
 * The emergency-shrink planner as it was at edcc31ff7, kept as a differential
 * reference for the linearized planner in src/core/compaction/compaction.ts.
 *
 * Do not edit this file to make a test pass: its whole value is that it is the old
 * search strategy - one full `measureShrinkAttempt` span walk per candidate cut -
 * verbatim. When the two planners disagree, the reference is the semantics and the
 * production planner is the bug.
 *
 * Everything below the import block is byte-identical to
 *
 *   git show edcc31ff7:packages/coding-agent/src/core/compaction/compaction.ts \
 *     | sed -n '120,149p;534,579p;824,975p'
 *
 * with exactly one delta: the exported name carries a `Reference` suffix. Verify with
 *
 *   diff <(git show edcc31ff7:packages/coding-agent/src/core/compaction/compaction.ts \
 *     | sed -n '120,149p;534,579p;824,975p') \
 *     <(tail -n +BODY packages/coding-agent/test/fixtures/emergency-shrink-reference.ts \
 *     | sed 's/planEmergencyShrinkReference/planEmergencyShrink/')
 *
 * where BODY is the line number of the first body line (the header above is the only
 * thing that may change it). `estimateTokensByContent` and the plan types are
 * imported from the live module on purpose: the pricing caliber is shared, so the
 * comparison isolates the cut search, which is what changed.
 */

import type { AgentMessage } from "@earendil-works/pi-agent-core";
import {
	EMERGENCY_SHRINK_TARGET_RATIO,
	type EmergencyShrinkPlan,
	type EmergencyShrinkSpan,
	estimateTokensByContent,
} from "../../src/core/compaction/compaction.js";
import {
	createBranchSummaryMessage,
	createCompactionSummaryMessage,
	createCustomMessage,
} from "../../src/core/messages.js";
import type { CompactionEntry, SessionEntry } from "../../src/core/session-manager.js";

/**
 * Extract AgentMessage from an entry if it produces one.
 * Returns undefined for entries that don't contribute to LLM context.
 */
function getMessageFromEntry(entry: SessionEntry): AgentMessage | undefined {
	if (entry.type === "message") {
		return entry.message;
	}
	if (entry.type === "custom_message") {
		return createCustomMessage(entry.customType, entry.content, entry.display, entry.details, entry.timestamp);
	}
	if (entry.type === "branch_summary") {
		return createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp);
	}
	if (entry.type === "compaction") {
		return createCompactionSummaryMessage(
			entry.summary,
			entry.tokensBefore,
			entry.timestamp,
			entry.customInstructions,
			undefined,
			// Fork addition (upstream #2098 left this path untouched): a rebuilt head
			// that drops the snapshot would silently downgrade a digest-carrying
			// compaction entry to a digest-free one.
			entry.harnessDigest,
		);
	}
	return undefined;
}

/**
 * Find valid cut points: indices of user, assistant, custom, or bashExecution messages.
 * Never cut at tool results (they must follow their tool call).
 * When we cut at an assistant message with tool calls, its tool results follow it
 * and will be kept.
 * BashExecutionMessage is treated like a user message (user-initiated context).
 */
function findValidCutPoints(entries: SessionEntry[], startIndex: number, endIndex: number): number[] {
	const cutPoints: number[] = [];
	for (let i = startIndex; i < endIndex; i++) {
		const entry = entries[i];
		switch (entry.type) {
			case "message": {
				const role = entry.message.role;
				switch (role) {
					case "bashExecution":
					case "custom":
					case "branchSummary":
					case "compactionSummary":
					case "user":
					case "assistant":
						cutPoints.push(i);
						break;
					case "toolResult":
						break;
				}
				break;
			}
			case "thinking_level_change":
			case "model_change":
			case "compaction":
			case "branch_summary":
			case "custom":
			case "custom_message":
			case "label":
			case "session_info":
				break;
		}
		// Branch summaries and custom messages are user-role turn boundaries.
		if (entry.type === "branch_summary" || entry.type === "custom_message") {
			cutPoints.push(i);
		}
	}
	return cutPoints;
}

/** Whether an entry is one of the summary-carrying kinds the shrink refuses to drop. */
function isSummaryEntry(entry: SessionEntry): boolean {
	if (entry.type === "compaction" || entry.type === "branch_summary") return true;
	if (entry.type !== "message") return false;
	return entry.message.role === "compactionSummary" || entry.message.role === "branchSummary";
}

function entrySummaryText(entry: SessionEntry): string {
	if (entry.type === "compaction" || entry.type === "branch_summary") return entry.summary ?? "";
	if (entry.type !== "message") return "";
	const message = entry.message;
	return message.role === "compactionSummary" || message.role === "branchSummary" ? message.summary : "";
}

function entryContextTokens(entry: SessionEntry): number {
	const message = getMessageFromEntry(entry);
	return message ? estimateTokensByContent(message) : 0;
}

interface ShrinkAttempt {
	cut: number;
	tokensAfter: number;
	span: EmergencyShrinkSpan;
	carriedSummaries: Array<{ kind: "compaction" | "branch"; text: string }>;
}

function measureShrinkAttempt(pathEntries: SessionEntry[], spanStart: number, cut: number): ShrinkAttempt {
	const carriedSummaries: Array<{ kind: "compaction" | "branch"; text: string }> = [];
	let carriedTokens = 0;
	let droppedEntries = 0;
	let droppedTokens = 0;
	const droppedRoles: Record<string, number> = {};
	let firstDroppedTimestamp: string | undefined;
	let lastDroppedTimestamp: string | undefined;
	let suffixTokens = 0;
	for (let i = spanStart; i < pathEntries.length; i++) {
		const entry = pathEntries[i];
		if (i >= cut) {
			suffixTokens += entryContextTokens(entry);
			continue;
		}
		if (isSummaryEntry(entry)) {
			const text = entrySummaryText(entry);
			if (!text) continue;
			carriedSummaries.push({ kind: summaryEntryKind(entry), text });
			carriedTokens += entryContextTokens(entry);
			continue;
		}
		const message = getMessageFromEntry(entry);
		if (!message) continue;
		const tokens = estimateTokensByContent(message);
		droppedEntries += 1;
		droppedTokens += tokens;
		const role = entry.type === "message" ? entry.message.role : entry.type;
		droppedRoles[role] = (droppedRoles[role] ?? 0) + 1;
		firstDroppedTimestamp ??= entry.timestamp;
		lastDroppedTimestamp = entry.timestamp;
	}
	return {
		cut,
		tokensAfter: carriedTokens + suffixTokens,
		span: { droppedEntries, droppedTokens, droppedRoles, firstDroppedTimestamp, lastDroppedTimestamp },
		carriedSummaries,
	};
}

function summaryEntryKind(entry: SessionEntry): "compaction" | "branch" {
	if (entry.type === "compaction") return "compaction";
	if (entry.type === "message" && entry.message.role === "compactionSummary") return "compaction";
	return "branch";
}

/**
 * Plan a lossy emergency shrink: the last resort when compaction keeps failing
 * while the context sits above the trigger threshold, so every further request is
 * headed for the provider's input wall.
 *
 * It drops the oldest NON-summary context entries until the estimate lands under
 * `thresholdTokens * EMERGENCY_SHRINK_TARGET_RATIO`, carrying any summary inside
 * the dropped span forward instead of losing it. The cut is always a valid cut
 * point, so no tool result is separated from the tool call it answers - a provider
 * rejects that pair outright, which would turn the shrink into a new failure.
 *
 * Both token figures are pure content-density sums over the same entries, so the
 * comparison is self-consistent; they are not the usage-anchored caliber
 * estimateContextTokens reports while a readable assistant usage exists.
 *
 * Returns undefined when there is nothing to do: no threshold, already under the
 * target, or no cut point to move to.
 */
export function planEmergencyShrinkReference(
	pathEntries: SessionEntry[],
	thresholdTokens: number,
	targetRatio: number = EMERGENCY_SHRINK_TARGET_RATIO,
): EmergencyShrinkPlan | undefined {
	if (thresholdTokens <= 0 || pathEntries.length === 0) return undefined;
	const targetTokens = Math.floor(thresholdTokens * targetRatio);

	let lastCompactionIndex = -1;
	for (let i = pathEntries.length - 1; i >= 0; i--) {
		if (pathEntries[i].type === "compaction") {
			lastCompactionIndex = i;
			break;
		}
	}
	// The context a new compaction entry would replace starts at the newest
	// boundary's retained entry (or at the head of the branch when there is none);
	// the cut itself stays after the boundary, because entries before it are already
	// represented by that boundary's summary.
	let spanStart = 0;
	let cutStart = 0;
	if (lastCompactionIndex >= 0) {
		const boundary = pathEntries[lastCompactionIndex] as CompactionEntry;
		const keptIndex = pathEntries.findIndex((entry) => entry.id === boundary.firstKeptEntryId);
		spanStart = keptIndex >= 0 ? keptIndex : lastCompactionIndex;
		cutStart = lastCompactionIndex + 1;
	}
	const cutPoints = findValidCutPoints(pathEntries, cutStart, pathEntries.length).filter((index) => index > spanStart);
	if (cutPoints.length === 0) return undefined;

	const tokensBefore = measureShrinkAttempt(pathEntries, spanStart, spanStart).tokensAfter;
	if (tokensBefore <= targetTokens) return undefined;

	let deepest: ShrinkAttempt | undefined;
	for (const cut of cutPoints) {
		const attempt = measureShrinkAttempt(pathEntries, spanStart, cut);
		deepest = attempt;
		if (attempt.tokensAfter <= targetTokens) return toPlan(pathEntries, attempt, tokensBefore, targetTokens, true);
	}
	if (!deepest) return undefined;
	return toPlan(pathEntries, deepest, tokensBefore, targetTokens, false);
}

function toPlan(
	pathEntries: SessionEntry[],
	attempt: ShrinkAttempt,
	tokensBefore: number,
	targetTokens: number,
	reachedTarget: boolean,
): EmergencyShrinkPlan {
	const entry = pathEntries[attempt.cut];
	return {
		firstKeptEntryId: entry.id,
		firstKeptEntryIndex: attempt.cut,
		tokensBefore,
		tokensAfter: attempt.tokensAfter,
		targetTokens,
		reachedTarget,
		span: attempt.span,
		carriedSummaries: attempt.carriedSummaries,
	};
}
