/**
 * The watchdog reports; the parent decides.
 *
 * A silent child used to reach its parent only as a kill: the failure notice is
 * generated by the abort, so a warn-only watchdog would have traded a false kill for
 * no signal at all. This pins the replacement contract - the warn stage delivers a
 * notice into the parent's own transcript, nothing is killed because of silence, and
 * the notice carries the facts (silent seconds, in-flight tool) plus the parent's own
 * lever for the wedge case.
 */
import type { AgentTool } from "@earendil-works/pi-agent-core";
import { fauxAssistantMessage, fauxToolCall } from "@earendil-works/pi-ai";
import { Type } from "typebox";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
	type CustomMessage,
	RLM_CHILD_FAILURE_CUSTOM_TYPE,
	RLM_CHILD_STALL_NOTICE_CUSTOM_TYPE,
	type RlmChildStallNoticeDetails,
} from "../../src/core/messages.js";
import { createHarness, type Harness } from "./harness.js";

function hangTool(): AgentTool {
	return {
		name: "hang_forever",
		label: "Hang Forever",
		description: "A tool that never returns",
		parameters: Type.Object({}),
		execute: () => new Promise<never>(() => {}),
	};
}

function messagesOfType(messages: readonly unknown[], customType: string): CustomMessage[] {
	return messages.filter(
		(message): message is CustomMessage =>
			typeof message === "object" &&
			message !== null &&
			(message as { role?: unknown }).role === "custom" &&
			(message as { customType?: unknown }).customType === customType,
	);
}

describe("a silent child is reported to its parent, not killed for it", () => {
	const harnesses: Harness[] = [];

	afterEach(() => {
		while (harnesses.length > 0) {
			harnesses.pop()?.cleanup();
		}
	});

	function track(harness: Harness): Harness {
		harnesses.push(harness);
		return harness;
	}

	async function wedgedChild(stallWatchdog: {
		enabled: boolean;
		warnAfterSeconds: number;
		abortAfterSeconds: number;
	}) {
		const child = track(
			await createHarness({
				tools: [hangTool()],
				settings: { stallWatchdog, retry: { enabled: false } },
				agentMessageController: {
					listAgents: () => ({ agents: [] }),
					sendAgentMessage: vi.fn(async () => {
						throw new Error("synthesized stall notices must not use agent_message");
					}),
				},
			}),
		);
		child.setResponses([fauxAssistantMessage(fauxToolCall("hang_forever", {}), { stopReason: "toolUse" })]);
		const parent = track(
			await createHarness({
				rlmDepth: 0,
				rlmMaxDepth: 1,
				subagentRuntimeHost: {
					createRlmSubagentRuntime: async () => ({ session: child.session }),
					deleteRlmSubagentRuntime: async () => {},
				},
			}),
		);
		await parent.session.runRlmChild("hang inside a tool", { name: "long-worker" });
		return { child, parent };
	}

	it("warn-only: the parent is told, and the child is left running", async () => {
		const { child, parent } = await wedgedChild({ enabled: true, warnAfterSeconds: 0.05, abortAfterSeconds: 0 });

		await vi.waitFor(
			() => {
				expect(messagesOfType(parent.session.messages, RLM_CHILD_STALL_NOTICE_CUSTOM_TYPE)).toHaveLength(1);
			},
			{ timeout: 15_000, interval: 20 },
		);

		const notice = messagesOfType(parent.session.messages, RLM_CHILD_STALL_NOTICE_CUSTOM_TYPE)[0]!;
		const details = notice.details as RlmChildStallNoticeDetails;
		expect(details.sessionName).toBe("long-worker");
		expect(details.silentMs).toBeGreaterThanOrEqual(details.thresholdMs);
		expect(details.inFlightTools.join(",")).toContain("hang_forever");
		// The notice has to name the parent's own lever: telling a parent to intervene
		// without saying how is how a report becomes noise.
		expect(notice.content).toContain("long-worker");
		expect(notice.content).toContain("hang_forever");
		expect(notice.content).toContain("rlm.delete_subagent");
		// Warn-only watchdog: the copy must not promise an abort that cannot happen.
		expect(notice.content).toContain("warn-only");

		// Nothing was killed for the silence: no abort event, no failure notice.
		expect(child.eventsOfType("stall_abort")).toEqual([]);
		const snapshots = parent.session.getRlmChildSnapshots();
		expect(snapshots.length).toBeGreaterThan(0);
		expect(snapshots[0]?.status).toBe("running");
		expect(messagesOfType(parent.session.messages, RLM_CHILD_FAILURE_CUSTOM_TYPE)).toEqual([]);
	});

	it("with an abort configured, the notice is the early signal and the kill notice still follows", async () => {
		const { child, parent } = await wedgedChild({ enabled: true, warnAfterSeconds: 0.05, abortAfterSeconds: 0.1 });

		await vi.waitFor(
			() => {
				expect(messagesOfType(parent.session.messages, RLM_CHILD_STALL_NOTICE_CUSTOM_TYPE)).toHaveLength(1);
			},
			{ timeout: 15_000, interval: 20 },
		);
		const notice = messagesOfType(parent.session.messages, RLM_CHILD_STALL_NOTICE_CUSTOM_TYPE)[0]!;
		expect((notice.details as RlmChildStallNoticeDetails).abortAfterMs).toBeGreaterThan(0);
		expect(notice.content).toContain("abort the turn after");

		await vi.waitFor(
			() => {
				expect(messagesOfType(parent.session.messages, RLM_CHILD_FAILURE_CUSTOM_TYPE)).toHaveLength(1);
			},
			{ timeout: 15_000, interval: 20 },
		);
		expect(child.eventsOfType("stall_abort")).toHaveLength(1);
	});
});
